# Success Messages
SUCCESS_REGISTRATION_PASSED = "Registered Successfully!"
SUCCESS_LOGIN_PASSED = "Logged In Successfully!"
SUCCESS_LOGOUT_PASS = "Logged Out Successfully!"
SUCCESS_OTP_VERIFICATION_PASSED = "Otp Verified Successfully!"
SUCCESS_OTP_SEND_PASSED = "New Otp Sent Successfully!!"
SUCCESS_DATA_INSERTION_PASSED = "Data Inserted Successfully!"
SUCCESS_DATA_UPDATION_PASSED = "Data Updated Successfully!"
SUCCESS_DATA_DELETION_PASSED = "Data Deleted Successfully!"
SUCCESS_DATA_SHOW_PASSED = "Data Found Successfully!"
SUCCESS_DATA_LIST_PASSED = "Data Listed Successfully!"
SUCCESS_NEW_TOKEN_PASSED = "New Token Send Successfully!"
SUCCESS_PASSWORD_UPDATE = "Password Changed Successfully!"

# Error Messages
ERROR_VALIDATION = "Validation Error!"
ERROR_SERVER = "Server Error: Something Went Wrong!"
ERROR_FORBIDDEN = "Forbidden Access!"
ERROR_UNAUTHORIZED = "Unauthorized Access!"
ERROR_BADREQUEST = "Bad Request!"
ERROR_CONFLICT = "Data Already Exists!"
ERROR_NOTFOUND = "Data Not Found!"
ERROR_VERIFICATION = "Invalid Otp!"
ERROR_LOGIN = "Invalid Credentials!"
ERROR_OLD_PASSWORD = "Invalid Old Password!"
